#' Journal Impact & Productivity Analysis (Lollipop Chart)
#'
#' @description
#' A sophisticated visualization using a "Lollipop" design to rank the top journals.
#' It helps identify "Core Sources" by visualizing three metrics simultaneously:
#' 1. Volume (Stick length)
#' 2. Total Citations (Bubble Size)
#' 3. Impact/Quality (Bubble Color - CPP mapped to a continuous palette)
#'
#' @param data A data frame containing bibliographic data.
#' @param source_col String. Column name for Source Title (default: "Source.title" or "Source title").
#' @param cite_col String. Column name for Citations (default: "Cited by").
#' @param top_n Integer. Number of journals to analyze (default: 10).
#' @param palette String. A continuous color palette name for the CPP mapping (default: "viridis"). Options: "magma", "plasma", "inferno", "cividis", "mako", "rocket", "turbo".
#'
#' @importFrom dplyr group_by summarize mutate arrange desc filter n
#' @importFrom ggplot2 ggplot aes geom_segment geom_point scale_size_continuous scale_color_viridis_c labs theme_minimal coord_flip geom_text annotate scale_y_continuous expansion theme element_text element_blank margin
#' @importFrom stringr str_to_title str_trunc
#' @importFrom rlang sym !!
#' @importFrom utils head
#' @export
#'
#' @examples
#' \dontrun{
#' # Default (Viridis Palette - Green/Blue/Yellow)
#' alman_bib_A4c_ProductivityJournal(df_herbal_dengue)
#'
#' # Magma Theme (Black/Purple/Orange/Yellow)
#' alman_bib_A4c_ProductivityJournal(df_herbal_dengue, palette = "magma")
#'
#' # Plasma Theme
#' alman_bib_A4c_ProductivityJournal(df_herbal_dengue, palette = "plasma")
#' }
alman_bib_A4c_ProductivityJournal <- function(data,
                                              source_col = "Source.title",
                                              cite_col = "Cited by",
                                              top_n = 10,
                                              palette = "viridis") {

  # ==========================================
  # 1. DATA PREPARATION
  # ==========================================
  if(!source_col %in% names(data)) stop(paste0("Error: '", source_col, "' column not found."))

  # Robust Citation Check
  possible_cites <- c(cite_col, "Cited.by", "Cited_by", "TC", "Cites", "Times.Cited")
  actual_cite_col <- NULL
  for(col in possible_cites) { if(col %in% names(data)) { actual_cite_col <- col; break } }

  if(is.null(actual_cite_col)) {
    data$Target_Cites <- 0
    warning("Citation column not found. Impact metrics will be 0.")
  } else {
    data$Target_Cites <- as.numeric(as.character(data[[actual_cite_col]]))
    data$Target_Cites[is.na(data$Target_Cites)] <- 0
  }

  # Clean NA from source column safely using base R to avoid evaluation errors
  df_clean <- data[!is.na(data[[source_col]]) & data[[source_col]] != "", , drop = FALSE]

  # Aggregate Data
  sym_source <- rlang::sym(source_col)

  journal_stats_full <- df_clean %>%
    dplyr::group_by(Journal = !!sym_source) %>%
    dplyr::summarize(
      Total_Docs = dplyr::n(),
      Total_Cites = sum(Target_Cites, na.rm=TRUE)
    ) %>%
    dplyr::mutate(
      CPP = round(Total_Cites / Total_Docs, 2),
      # Clean names: Title Case and Truncate if too long
      Journal_Display = stringr::str_trunc(stringr::str_to_title(Journal), 50)
    ) %>%
    dplyr::arrange(dplyr::desc(Total_Docs))

  # Replace slice_max with head for safe generic dispatch
  journal_stats <- utils::head(journal_stats_full, top_n)

  # Reorder for Plotting (Factor)
  journal_stats$Journal_Display <- factor(journal_stats$Journal_Display,
                                          levels = journal_stats$Journal_Display[order(journal_stats$Total_Docs)])

  # ==========================================
  # 2. VISUALIZATION (Lollipop Chart)
  # ==========================================

  # Footer as requested
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ",
                        format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  p <- ggplot2::ggplot(journal_stats, ggplot2::aes(x = Journal_Display, y = Total_Docs)) +

    # 1. The Stick (Segment) - Adjusted size to linewidth to prevent warning
    ggplot2::geom_segment(ggplot2::aes(x = Journal_Display, xend = Journal_Display, y = 0, yend = Total_Docs),
                          color = "gray80", linewidth = 1) +

    # 2. The Lollipop Head (Point) - Color mapped to CPP via Viridis
    ggplot2::geom_point(ggplot2::aes(size = Total_Cites, color = CPP), alpha = 0.9) +

    # 3. Text Label (Volume Count at the end of stick, but slightly offset)
    ggplot2::geom_text(ggplot2::aes(label = Total_Docs),
                       color = "gray40", size = 3, fontface = "bold",
                       nudge_y = max(journal_stats$Total_Docs) * 0.05) +

    # 4. Text Label (CPP context inside plot area)
    ggplot2::annotate("text", x = 1, y = max(journal_stats$Total_Docs),
                      label = paste0("Color = Impact (CPP)\nSize = Citations"),
                      hjust = 1, vjust = 0, size = 3, color = "gray50", fontface = "italic") +

    # 5. Scales
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.1))) +
    ggplot2::scale_size_continuous(range = c(4, 12), name = "Total Citations") +
    ggplot2::scale_color_viridis_c(option = palette, name = "Cites per Paper") + # <- UPDATED TO CONTINUOUS PALETTE

    # 6. Theme & Labs
    ggplot2::coord_flip() + # Flip to make it readable list
    ggplot2::labs(title = "Core Journal Impact Analysis",
                  subtitle = paste0("Top ", top_n, " Most Productive Journals ranked by Volume"),
                  x = "", # No X label needed as names are self-explanatory
                  y = "Number of Articles (Volume)",
                  caption = footer_text) +

    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 14),
      plot.subtitle = ggplot2::element_text(face = "italic", size = 10, color = "gray40"),
      axis.text.y = ggplot2::element_text(face = "bold", size = 10, color = "#2c3e50"),
      panel.grid.major.y = ggplot2::element_blank(), # Clean horizontal lines
      panel.grid.minor = ggplot2::element_blank(),
      legend.position = "right",
      plot.caption = ggplot2::element_text(color = "gray60", size = 8, margin = ggplot2::margin(t = 10))
    )

  return(p)
}
