#' Sophisticated Statistical Word Cloud
#'
#' @description
#' A professional word cloud that goes beyond simple visualization.
#' It calculates the 'Shannon Entropy' (Thematic Diversity) and
#' displays it alongside the word cloud.
#' Features:
#' 1. Density-optimized layout (words fit tightly).
#' 2. Gradient coloring based on frequency mapped to a continuous palette.
#' 3. Integrated statistical insights (Entropy, Unique Terms).
#'
#' @param data A data frame containing bibliographic data.
#' @param keyword_col String. Column name for keywords (default: "Author.Keywords").
#' @param top_n Integer. Number of keywords to display (default: 70).
#' @param min_freq Integer. Minimum frequency to be included (default: 2).
#' @param max_size Numeric. Maximum font size for the largest word (default: 40).
#' @param remove_terms Vector. Stopwords to remove.
#' @param palette String. A continuous color palette name for the frequency mapping (default: "viridis"). Options: "magma", "plasma", "inferno", "cividis", "mako", "rocket", "turbo".
#'
#' @importFrom stringr str_trim str_to_lower str_to_title
#' @importFrom dplyr select filter mutate group_by summarize arrange desc n
#' @importFrom ggplot2 ggplot aes scale_size_area scale_color_viridis_c labs theme_void theme element_text margin
#' @importFrom ggwordcloud geom_text_wordcloud_area
#' @importFrom tidyr separate_rows
#' @importFrom rlang sym !!
#' @importFrom utils head
#' @export
#' @examples
#' \dontrun{
#' # Standard Viridis Theme
#' alman_bib_A5b_Keyword_Cloud(df_herbal_tb)
#'
#' # Magma Theme (Black/Purple/Orange/Yellow)
#' alman_bib_A5b_Keyword_Cloud(df_herbal_tb, palette = "magma", max_size = 35)
#' }
alman_bib_A5b_Keyword_Cloud <- function(data,
                                    keyword_col = "Author.Keywords",
                                    top_n = 70,
                                    min_freq = 2,
                                    max_size = 40,
                                    remove_terms = c("article", "human", "priority journal", "review", "study",
                                                     "systematic review", "meta-analysis", "adult", "male", "female"),
                                    palette = "viridis") {

  # ==========================================
  # 1. DATA PREPARATION
  # ==========================================
  if(!keyword_col %in% names(data)) stop(paste0("Error: '", keyword_col, "' column not found."))

  # Extract and Clean safely
  sym_keyword <- rlang::sym(keyword_col)

  df_words <- data %>%
    dplyr::select(Keyword = !!sym_keyword) %>%
    dplyr::filter(!is.na(Keyword) & Keyword != "") %>%
    tidyr::separate_rows(Keyword, sep = ";") %>%
    dplyr::mutate(Keyword = stringr::str_trim(stringr::str_to_lower(Keyword))) %>%
    dplyr::filter(Keyword != "")

  # Remove Stopwords
  if(!is.null(remove_terms)) {
    df_words <- df_words %>%
      dplyr::filter(!Keyword %in% stringr::str_to_lower(remove_terms))
  }

  # Calculate Frequency
  word_freq <- df_words %>%
    dplyr::group_by(Keyword) %>%
    dplyr::summarize(Freq = dplyr::n()) %>%
    dplyr::filter(Freq >= min_freq) %>%
    dplyr::arrange(dplyr::desc(Freq))

  if(nrow(word_freq) == 0) stop("No keywords remaining after filtering. Try lowering min_freq or checking remove_terms.")

  # ==========================================
  # 2. STATISTICAL CALCULATION (Entropy)
  # ==========================================
  total_occurrences <- sum(word_freq$Freq)
  probs <- word_freq$Freq / total_occurrences
  shannon_entropy <- -sum(probs * log(probs))

  unique_terms <- nrow(word_freq)
  top_term <- word_freq$Keyword[1]
  top_term_pct <- round((word_freq$Freq[1] / total_occurrences) * 100, 1)

  # Filter for Plotting (Replace slice_max with head for safety)
  plot_data <- utils::head(word_freq, top_n)

  # Stats Label (Borderless)
  stats_label <- paste0(
    " Thematic Unique Terms: ", unique_terms, " |",
    " Shannon Entropy: ", round(shannon_entropy, 2), " (Diversity)"," |",
    " Top Focus: '", stringr::str_to_title(top_term), "' (", top_term_pct, "%)"
  )

  # ==========================================
  # 3. VISUALIZATION
  # ==========================================
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ",
                        format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  set.seed(42) # Consistent shape

  p <- ggplot2::ggplot(plot_data, ggplot2::aes(label = stringr::str_to_title(Keyword), size = Freq, color = Freq)) +

    # 1. The Word Cloud Layer
    ggwordcloud::geom_text_wordcloud_area(shape = "circle", eccentricity = 0.65, rm_outside = TRUE) +

    # 2. Scales - Using Continuous Palette as standard
    ggplot2::scale_size_area(max_size = max_size) +
    ggplot2::scale_color_viridis_c(option = palette) +

    # 4. Theme & Footer
    ggplot2::labs(title = "Semantic Landscape & Focus", subtitle = stats_label,
                  caption = footer_text) +

    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 16, hjust = 0.5, margin = ggplot2::margin(b = 10)),
      plot.subtitle = ggplot2::element_text(color = "gray30", size = 10, hjust = 0.5, margin = ggplot2::margin(b = 15)),
      plot.caption = ggplot2::element_text(color = "gray60", size = 8, margin = ggplot2::margin(t = 20)),
      plot.margin = ggplot2::margin(20, 20, 20, 20)
    )

  return(p)
}
