#' Global Productivity Heatmap
#'
#' @description
#' This function analyzes the geographical distribution of publications.
#' It automatically extracts country names from the "Affiliations" column,
#' standardizes them, and projects the publication frequency onto a world map.
#'
#' @param data A data frame containing the bibliographic data.
#' @param affil_col String. Column name for Affiliations (default: "Affiliations").
#' @param low_col Color for low productivity countries (default: "#d6eaf8").
#' @param high_col Color for high productivity countries (default: "#2980b9").
#' @param top_n_labels Integer. Jumlah top negara produktif yang ingin ditampilkan pada anotasi peta (default: 5).
#'
#' @importFrom stringr str_trim
#' @importFrom dplyr group_by summarize arrange desc n left_join
#' @importFrom ggplot2 ggplot aes geom_polygon scale_fill_gradient labs theme_void theme element_text coord_fixed annotate map_data margin unit
#' @importFrom utils head tail
#' @export
#'
#' @examples
#' \dontrun{
#' # 1. Standard Heatmap (Menampilkan Top 5 negara)
#' alman_bib_A3a_GlobalHeatmap(df_herbal_snakebite)
#'
#' # 2. Menampilkan Top 10 negara dengan tema warna "Fire" (Merah/Oranye)
#' alman_bib_A3a_GlobalHeatmap(
#'   data = df_herbal_snakebite,
#'   low_col = "#f6ddcc",
#'   high_col = "#e74c3c",
#'   top_n_labels = 10)
#' }

alman_bib_A3a_GlobalHeatmap <- function(data,
                                        affil_col = "Affiliations",
                                        low_col = "#d6eaf8",
                                        high_col = "#2980b9",
                                        top_n_labels = 5) { # <-- Parameter keluwesan Top N ditambahkan di sini

  # ==========================================
  # 1. DATA PREPARATION & EXTRACTION
  # ==========================================
  if(!affil_col %in% names(data)) stop(paste0("Error: '", affil_col, "' column not found."))

  # 1. Filter non-empty rows
  df_geo <- data[!is.na(data[[affil_col]]) & data[[affil_col]] != "", , drop = FALSE]

  # 2. CRITICAL FIX: Force column to be Character type
  df_geo[[affil_col]] <- as.character(df_geo[[affil_col]])

  # Helper function to extract country
  extract_country <- function(x) {
    if(is.na(x) || x == "") return(NA)

    # Split by semicolon (multiple affiliations)
    parts <- unlist(strsplit(x, ";"))

    # Take the last part of the address
    countries <- sapply(parts, function(p) {
      loc_parts <- unlist(strsplit(p, ","))
      # Robust check: if split failed, return original (fleksibel menggunakan sumber daya yang ada)
      if(length(loc_parts) > 0) {
        return(stringr::str_trim(utils::tail(loc_parts, 1)))
      } else {
        return(NA)
      }
    })
    return(unique(countries[!is.na(countries)]))
  }

  # Apply extraction
  country_list <- lapply(df_geo[[affil_col]], extract_country)

  # Flatten list to dataframe
  if(length(country_list) == 0) stop("No valid affiliations found to map.")

  df_countries <- data.frame(
    region = unlist(country_list),
    stringsAsFactors = FALSE
  )

  # ==========================================
  # 2. STANDARDIZATION (Fixing Names for Map)
  # ==========================================
  # Remove extra spaces/dots often found in Scopus data (e.g., "USA.")
  df_countries$region <- gsub("\\.", "", df_countries$region)

  # Standardize country names for maps compatibility
  df_countries$region <- gsub("United States", "USA", df_countries$region)
  df_countries$region <- gsub("United Kingdom", "UK", df_countries$region)
  df_countries$region <- gsub("England", "UK", df_countries$region)
  df_countries$region <- gsub("Korea", "South Korea", df_countries$region)
  df_countries$region <- gsub("Viet Nam", "Vietnam", df_countries$region)
  df_countries$region <- gsub("Russian Federation", "Russia", df_countries$region)

  # Count frequencies
  country_counts <- df_countries %>%
    dplyr::group_by(region) %>%
    dplyr::summarize(Docs = dplyr::n()) %>%
    dplyr::arrange(dplyr::desc(Docs))

  # ==========================================
  # 3. VISUALIZATION (World Map)
  # ==========================================
  # Memanggil map_data dari package peta
  world_map <- ggplot2::map_data("world")

  # Join Data
  map_plot_data <- dplyr::left_join(world_map, country_counts, by = "region")

  # Stats for Label (FLEXIBLE TOP N)
  top_n_df <- utils::head(country_counts, top_n_labels)
  top_n_str <- paste(paste0(1:nrow(top_n_df), ". ", top_n_df$region, " (", top_n_df$Docs, ")"), collapse = "\n")

  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ",
                        format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  p <- ggplot2::ggplot(map_plot_data, ggplot2::aes(x = long, y = lat, group = group)) +

    # 1. Base Map (Grey)
    ggplot2::geom_polygon(fill = "#f2f2f2", color = "white", linewidth = 0.1) +

    # 2. Heatmap Layer
    ggplot2::geom_polygon(ggplot2::aes(fill = Docs), color = "white", linewidth = 0.1) +

    # 3. Color Scale
    ggplot2::scale_fill_gradient(name = "Publications",
                                 low = low_col, high = high_col,
                                 na.value = "#f2f2f2",
                                 trans = "log1p",
                                 breaks = scales::breaks_pretty(n = 4)) +

    # 4. Text Annotation (Label kini otomatis menyesuaikan jumlah Top N)
    ggplot2::annotate("text", x = -170, y = -30, label = paste0("TOP ", top_n_labels, " PRODUCTIVE REGIONS:\n", top_n_str),
                      hjust = 0, vjust = 0, size = 3, family = "mono", color = "#2c3e50") +

    # 5. Theme & Labels
    ggplot2::labs(title = "Global Distribution of Scientific Production",
                  subtitle = paste0("Visualizing research output from ", nrow(country_counts), " unique regions"),
                  caption = footer_text) +

    ggplot2::coord_fixed(1.3) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 16, hjust = 0.5, margin = ggplot2::margin(b = 10)),
      plot.subtitle = ggplot2::element_text(size = 10, color = "gray50", hjust = 0.5, margin = ggplot2::margin(b = 20)),
      plot.caption = ggplot2::element_text(color = "gray60", size = 8, hjust = 0.95, margin = ggplot2::margin(t = 10)),
      legend.position = "bottom",
      legend.key.width = ggplot2::unit(2, "cm")
    )

  return(p)
}
