#' Advanced Bibliometric Trend Analysis
#'
#' @description
#' This function visualizes publication trends using a smooth area chart.
#' It includes Mann-Kendall and Pettitt's tests
#' around the statistics for a cleaner look.
#'
#' @param data A data frame containing the bibliographic data.
#' @param year_col A character string specifying the Year column (default: "Year").
#' @param fill_col Color for the area fill (default: "maroon").
#' @param line_col Color for the top line accent (default: "red").
#' @param alpha_val Transparency level for the fill (default: 0.6).
#'
#' @importFrom dplyr group_by summarize
#' @importFrom ggplot2 ggplot aes geom_area geom_line geom_vline geom_text labs theme_minimal theme geom_smooth scale_x_continuous
#' @importFrom trend mk.test pettitt.test
#' @returns A \code{ggplot2} object.
#' @export
#' @examples
#' \dontrun{
#' # 1. Standard (Maroon/Red look)
#' marsumy_A1_TrendAnalysis(df_patientsafety)
#'
#' # 2. Custom Colors
#' marsumy_A1_TrendAnalysis(df_herbal_leptospirosis, fill_col = "#2ecc71", line_col = "#27ae60", alpha_val = 0.5)
#' }

alman_bib_A1_TrendAnalysis <- function(data, year_col = "Year",
                                     fill_col = "maroon",
                                     line_col = "red",
                                     alpha_val = 0.6) {

  # ==========================================
  # 1. DATA PREPARATION
  # ==========================================
  if(!year_col %in% names(data)) stop(paste0("Error: '", year_col, "' column not found."))

  # Extract and Aggregate
  trend_data <- data[!is.na(data[[year_col]]), ]

  if(any(duplicated(trend_data[[year_col]]))) {
    agg_data <- as.data.frame(table(trend_data[[year_col]]))
    colnames(agg_data) <- c("Year", "n")
    agg_data$Year <- as.numeric(as.character(agg_data$Year))
  } else {
    agg_data <- trend_data[, c(year_col, 2)]
    colnames(agg_data) <- c("Year", "n")
  }

  # Filter & Sort
  agg_data <- agg_data[order(agg_data$Year), ]
  agg_data <- agg_data[agg_data$Year > 1900 & agg_data$Year < 2030, ]

  if(nrow(agg_data) < 5) stop("Error: Need at least 5 years of data for Mann-Kendall/Pettitt tests.")

  # Fill in missing years with 0
  full_years <- seq(min(agg_data$Year), max(agg_data$Year))
  agg_data <- merge(data.frame(Year = full_years), agg_data, all.x = TRUE)
  agg_data$n[is.na(agg_data$n)] <- 0

  # ==========================================
  # 2. ADVANCED STATISTICAL ANALYSIS
  # ==========================================
  time_series <- agg_data$n

  # A. Mann-Kendall Test
  mk_res <- trend::mk.test(time_series)
  mk_tau <- mk_res$estimates[["tau"]]
  mk_p   <- mk_res$p.value

  # B. Pettitt's Test
  pet_res <- trend::pettitt.test(time_series)
  pet_p   <- pet_res$p.value
  pet_idx <- pet_res$estimate
  change_point_year <- agg_data$Year[pet_idx]

  # C. CAGR & Slope
  slope <- coef(lm(n ~ Year, data = agg_data))[2]
  start_val <- head(agg_data$n[agg_data$n > 0], 1)
  if(is.na(start_val)) start_val <- 1
  end_val <- tail(agg_data$n, 1)
  n_years <- max(agg_data$Year) - min(agg_data$Year)
  cagr <- (end_val / start_val)^(1/n_years) - 1

  # D. Text Formatting
  mk_status <- ifelse(mk_p < 0.05, "Trend is Significant", "No Significant Trend")
  pet_status <- ifelse(pet_p < 0.05, paste0("Shift in ", change_point_year), "No Breakpoint")

  stats_label <- paste0(
    "Mann-Kendall (Trend):", " Tau: ", round(mk_tau, 2), " | P: ", format.pval(mk_p, digits=3), "\n",
    " Result: ", mk_status, "\n",
    "-------------------------", "\n",
    "Pettitt's Test (Change):", " Year: ", change_point_year, " | P: ", format.pval(pet_p, digits=3), "\n",
    " Result: ", pet_status, "\n",
    "-------------------------", "\n",
    "Growth (CAGR): ", round(cagr*100, 1), "%"
  )

  # ==========================================
  # 3. VISUALIZATION
  # ==========================================
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ",
                        format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  p <- ggplot2::ggplot(agg_data, ggplot2::aes(x = Year, y = n)) +

    # 1. Area Fill (No border, blended)
    ggplot2::geom_area(fill = fill_col, alpha = alpha_val) +

    # 2. Top Line
    ggplot2::geom_line(color = line_col, linewidth = 1) +

    # 3. Smooth Trend Line
    ggplot2::geom_smooth(method = "loess", se = FALSE, color = "black", linetype = "dotted", linewidth = 0.5) +

    # 4. Change Point Line (Vertical Dashed) - Only if Significant
    {if(pet_p < 0.05) ggplot2::geom_vline(xintercept = change_point_year, linetype="dashed", color="#c0392b", linewidth=0.8)} +

    # 5. Shift Label
    {if(pet_p < 0.05) ggplot2::annotate("text", x = change_point_year, y = max(agg_data$n),
                                        label = paste("Shift:", change_point_year),
                                        hjust = 1.1, vjust = 1, color = "#c0392b", size = 3, angle = 90)} +

    # 6. Stats Text (Clean, no box)
    ggplot2::annotate("text", x = -Inf, y = Inf, label = stats_label,
                      hjust = -0.05, vjust = 1.05, size = 3,
                      family = "mono", color = "black") +

    # 7. Force Integer Years on X-Axis (THE FIX)
    ggplot2::scale_x_continuous(breaks = function(x) {
      breaks <- pretty(x)
      breaks[breaks %% 1 == 0] # Keeps only the whole numbers
    }) +

    # 8. Labs & Theme
    ggplot2::labs(title = "Evolution of Scientific Production",
                  subtitle = paste0("Mann-Kendall Trend Test & Pettitt's Change Point Analysis (", min(agg_data$Year), "-", max(agg_data$Year), ")"),
                  x = "Year", y = "Documents",
                  caption = footer_text) +

    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 14),
      plot.subtitle = ggplot2::element_text(face = "italic", size = 10, color = "gray40"),
      axis.title = ggplot2::element_text(face = "bold"),
      plot.caption = ggplot2::element_text(color = "gray60", size = 8, margin = ggplot2::margin(t = 10)),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    )

  return(p)
}
